import { TablePropType } from "../components/table";
import {
    ArrowRightIcon,
    BoxIcon,
    CategoryImage,
    DiscountShapeIcon,
    InfoCircleIcon,
    LogoutIcon,
    ProfileIcon,
    SettingsIcon,
    TrendUpIcon,
    GuyImage,
    Guy2Image,
    GirlImage,
    Girl2Image,
    LadyImage,
    ShoppingImage,
    BoxTickImage,
    RotateImage,
    CoinImage,
} from "../utils/images";

export const linkData = [
    {
        id: 1,
        title: "Dashboard",
        imgSrc: CategoryImage,
    },
    {
        id: 2,
        title: "Trend",
        imgSrc: TrendUpIcon,
    },
    {
        id: 3,
        title: "Profile",
        imgSrc: ProfileIcon,
    },
    {
        id: 4,
        title: "Box",
        imgSrc: BoxIcon,
    },
    {
        id: 5,
        title: "Discount",
        imgSrc: DiscountShapeIcon,
    },
    {
        id: 6,
        title: "Info",
        imgSrc: InfoCircleIcon,
    },
    {
        id: 7,
        title: "Close",
        imgSrc: ArrowRightIcon,
    },
    {
        id: 8,
        title: "Settings",
        imgSrc: SettingsIcon,
    },
    {
        id: 9,
        title: "Logout",
        imgSrc: LogoutIcon,
    },
];

export const weeklyChartData = [
    { name: "Week 1", amount: 1200 },
    { name: "Week 2", amount: 1800 },
    { name: "Week 3", amount: 2500 },
    { name: "Week 4", amount: 3000 },
    { name: "Week 5", amount: 2800 },
    { name: "Week 6", amount: 3500 },
    { name: "Week 7", amount: 4000 },
    { name: "Week 8", amount: 4500 },
    { name: "Week 9", amount: 5000 },
    { name: "Week 10", amount: 5500 },
    { name: "Week 11", amount: 6000 },
    { name: "Week 12", amount: 6500 },
];

export const chartData = [
    { name: "Jan", amount: 6000 },
    { name: "Feb", amount: 17000 },
    { name: "Mar", amount: 3500 },
    { name: "Apr", amount: 28000 },
    { name: "May", amount: 8000 },
    { name: "Jun", amount: 45000 },
    { name: "Jul", amount: 8000 },
    { name: "Aug", amount: 18000 },
    { name: "Sep", amount: 35000 },
    { name: "Oct", amount: 4000 },
    { name: "Nov", amount: 25000 },
    { name: "Dec", amount: 21000 },
];

export const yearlyChartData = [
    { name: "2015", amount: 6000 },
    { name: "2016", amount: 9000 },
    { name: "2017", amount: 12000 },
    { name: "2018", amount: 15000 },
    { name: "2019", amount: 18000 },
    { name: "2020", amount: 21000 },
    { name: "2021", amount: 24000 },
    { name: "2022", amount: 27000 },
    { name: "2023", amount: 30000 },
    { name: "2024", amount: 33000 },
    { name: "2025", amount: 36000 },
    { name: "2026", amount: 39000 },
];

export const tableData: TablePropType["tableData"] = [
    {
        id: 1,
        name: "Marcus Bergson",
        imgSrc: Guy2Image,
        date: "Nov 15, 2023",
        amount: "$80,000",
        status: "Paid",
    },
    {
        id: 2,
        name: "Jaydon Vaccaro",
        imgSrc: LadyImage,
        date: "Nov 14, 2023",
        amount: "$150,000",
        status: "Refund",
    },
    {
        id: 3,
        name: "Corey Schleifer",
        imgSrc: GirlImage,
        date: "Nov 13, 2023",
        amount: "$87,000",
        status: "Paid",
    },
    {
        id: 4,
        name: "Cooper Press",
        imgSrc: Girl2Image,
        date: "Nov 12, 2023",
        amount: "$100,000",
        status: "Paid",
    },
    {
        id: 5,
        name: "Phillip Lubin",
        imgSrc: GuyImage,
        date: "Nov 15, 2023",
        amount: "$80,000",
        status: "Paid",
    },
    {
        id: 6,
        name: "Floyd Miles",
        imgSrc: Guy2Image,
        date: "Nov 18, 2023",
        amount: "$75,000",
        status: "Refund",
    },
    {
        id: 7,
        name: "Emily Smith",
        imgSrc: LadyImage,
        date: "Nov 19, 2023",
        amount: "$120,000",
        status: "Paid",
    },
    {
        id: 8,
        name: "Ethan Hunt",
        imgSrc: GuyImage,
        date: "Nov 20, 2023",
        amount: "$90,000",
        status: "Paid",
    },
    {
        id: 9,
        name: "Liam Johnson",
        imgSrc: Guy2Image,
        date: "Nov 21, 2023",
        amount: "$110,000",
        status: "Refund",
    },
    {
        id: 10,
        name: "Olivia Davis",
        imgSrc: GirlImage,
        date: "Nov 22, 2023",
        amount: "$95,000",
        status: "Paid",
    },
    {
        id: 11,
        name: "Sophia Clark",
        imgSrc: Girl2Image,
        date: "Nov 23, 2023",
        amount: "$130,000",
        status: "Paid",
    },
    {
        id: 12,
        name: "Noah Thompson",
        imgSrc: GuyImage,
        date: "Nov 24, 2023",
        amount: "$85,000",
        status: "Paid",
    },
];

export const platformData = [
    {
        id: 1,
        name: "Book Bazaar",
        percent: 15,
        amount: 2500000,
        color: "#6160DC",
    },
    {
        id: 2,
        name: "Artisan Aisle",
        percent: 10,
        amount: 1800000,
        color: "#54C5EB",
    },
    {
        id: 3,
        name: "Crafts Corner",
        percent: 8,
        amount: 1200000,
        color: "#FFB74A",
    },
    {
        id: 4,
        name: "XStore",
        percent: 5,
        amount: 700000,
        color: "#34CAA5",
    },
    {
        id: 5,
        name: "Tech Treasures",
        percent: 12,
        amount: 2100000,
        color: "#FF5252",
    },
    {
        id: 6,
        name: "Gourmet Goods",
        percent: 18,
        amount: 3200000,
        color: "#6EC177",
    },
    {
        id: 7,
        name: "Fashion Finds",
        percent: 7,
        amount: 950000,
        color: "#F7931E",
    },
    {
        id: 8,
        name: "Home Hub",
        percent: 14,
        amount: 2000000,
        color: "#9C27B0",
    },
];

export const cardData = [
    {
        id: 1,
        imgSrc: BoxTickImage,
        title: "Total Order",
        amount: 350,
        trend: "up",
    },
    {
        id: 2,
        imgSrc: RotateImage,
        title: "Total Refund",
        amount: 270,
        trend: "down",
    },
    {
        id: 3,
        imgSrc: ShoppingImage,
        title: "Average Sales",
        amount: 1567,
        trend: "down",
    },
    {
        id: 4,
        imgSrc: CoinImage,
        title: "Total Income",
        amount: "$350.000",
        trend: "up",
    },
];
